version: '3.3'
services:
  ckb:
    image: tockb/ckb-dev:v0.39.2
    ports:
      - '8114:8114'
    networks:
      forcenet:
        ipv4_address: 10.5.0.11
        aliases:
          - ckb
  ckb-indexer:
    image: tockb/ckb-indexer:ab57116
    ports:
      - '8116:8116'
    environment:
      - RUST_LOG=info
    command: ckb-indexer -s /tmp/ckb-indexer-test -c http://ckb:8114 -l 0.0.0.0:8116
    depends_on:
      - ckb
    networks:
      forcenet:
        ipv4_address: 10.5.0.12
        aliases:
          - ckb-indexer
networks:
  forcenet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
